// frontend/config.js
// API Configuration - Auto-generated by Terraform
// DO NOT EDIT MANUALLY - This file is generated during deployment

window.CONFIG = {
  // API Gateway URL
  API_URL: window.location.hostname === 'localhost' 
    ? 'http://localhost:3001'
    : 'https://3wowpl5onl.execute-api.us-east-1.amazonaws.com/prod',
  
  // Email domain for user accounts
  EMAIL_DOMAIN: 'blumenfeld.com'
};

// Backward compatibility
window.API_CONFIG = {
  BASE_URL: window.CONFIG.API_URL
};
