#!/bin/bash

# AI Agents Platform Deployment Script
# Automates infrastructure deployment and frontend configuration

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=====================================${NC}"
echo -e "${BLUE}AI Multi-Agents Platform Deployment${NC}"
echo -e "${BLUE}=====================================${NC}"
echo ""

# Get environment (dev or prod)
ENVIRONMENT="${1:-dev}"
echo -e "${YELLOW}Environment: ${ENVIRONMENT}${NC}"

# Navigate to terraform directory
cd "$(dirname "$0")/terraform"

# Get account ID
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null)
if [ -z "$ACCOUNT_ID" ]; then
  echo -e "${RED}ERROR: Could not determine AWS Account ID${NC}"
  echo "Please ensure AWS CLI is configured: aws configure"
  exit 1
fi
echo -e "${GREEN}AWS Account ID: ${ACCOUNT_ID}${NC}"

# Check if tfvars file exists
if [ ! -f "env/${ENVIRONMENT}.tfvars" ]; then
  echo -e "${RED}ERROR: env/${ENVIRONMENT}.tfvars not found${NC}"
  exit 1
fi

# Initialize Terraform
echo -e "${BLUE}Initializing Terraform...${NC}"
terraform init

# Plan
echo -e "${BLUE}Planning infrastructure changes...${NC}"
terraform plan -var-file="env/${ENVIRONMENT}.tfvars" -var="account_id=${ACCOUNT_ID}" -out=tfplan

# Confirm
echo ""
read -p "Apply these changes? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
  echo -e "${YELLOW}Deployment cancelled${NC}"
  rm -f tfplan
  exit 0
fi

# Apply
echo -e "${BLUE}Applying infrastructure changes...${NC}"
terraform apply tfplan
rm -f tfplan

# Get outputs
echo -e "${BLUE}Getting deployment outputs...${NC}"
API_ENDPOINT=$(terraform output -raw api_endpoint)
FRONTEND_BUCKET=$(terraform output -raw frontend_bucket)
CLOUDFRONT_URL=$(terraform output -raw frontend_url)
CLOUDFRONT_DIST_ID=$(terraform output -raw cloudfront_distribution_id)

echo -e "${GREEN}✅ Infrastructure deployed successfully!${NC}"
echo ""
echo -e "${BLUE}Deployment Details:${NC}"
echo -e "  API Endpoint: ${YELLOW}${API_ENDPOINT}${NC}"
echo -e "  Frontend Bucket: ${YELLOW}${FRONTEND_BUCKET}${NC}"
echo -e "  CloudFront URL: ${YELLOW}${CLOUDFRONT_URL}${NC}"
echo ""

# Update frontend config.js (already generated by Terraform)
echo -e "${BLUE}Frontend config.js has been generated by Terraform${NC}"

# Upload frontend to S3
echo -e "${BLUE}Uploading frontend files to S3...${NC}"
cd ../frontend
aws s3 sync . "s3://${FRONTEND_BUCKET}/" \
  --exclude "*.md" \
  --exclude ".DS_Store" \
  --cache-control "public,max-age=300" \
  --metadata-directive REPLACE

echo -e "${GREEN}✅ Frontend files uploaded${NC}"

# Invalidate CloudFront cache
echo -e "${BLUE}Invalidating CloudFront cache...${NC}"
INVALIDATION_ID=$(aws cloudfront create-invalidation \
  --distribution-id "${CLOUDFRONT_DIST_ID}" \
  --paths "/*" \
  --query 'Invalidation.Id' \
  --output text)

echo -e "${GREEN}✅ CloudFront invalidation created: ${INVALIDATION_ID}${NC}"
echo -e "${YELLOW}Note: Cache invalidation may take 5-15 minutes to complete${NC}"

# Summary
echo ""
echo -e "${GREEN}=====================================${NC}"
echo -e "${GREEN}Deployment Complete!${NC}"
echo -e "${GREEN}=====================================${NC}"
echo ""
echo -e "${BLUE}Access your application:${NC}"
echo -e "  ${YELLOW}${CLOUDFRONT_URL}${NC}"
echo ""
echo -e "${BLUE}API Endpoint:${NC}"
echo -e "  ${YELLOW}${API_ENDPOINT}${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  1. Wait for CloudFront invalidation to complete (~10 minutes)"
echo "  2. Access your frontend at the CloudFront URL above"
echo "  3. Login with your seeded user credentials"
echo ""
echo -e "${YELLOW}Test your deployment:${NC}"
echo "  cd ../tests"
echo "  ./integration_tests.sh"
echo ""
