// frontend/config.js
// API Configuration - Auto-generated by Terraform
// DO NOT EDIT MANUALLY - This file is generated during deployment

window.CONFIG = {
  // API Gateway URL
  API_URL: window.location.hostname === 'localhost' 
    ? 'http://localhost:3001'
    : '${api_url}',
  
  // Email domain for user accounts
  EMAIL_DOMAIN: '${email_domain}'
};

// Backward compatibility
window.API_CONFIG = {
  BASE_URL: window.CONFIG.API_URL
};
